<a href="https://colab.research.google.com/github/aniket02k/Machine-Learning/blob/main/Linear_Algebra_Hands_On.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True) #Clear printing no scientific notation

# **1. Scalar, Vectors, Matrix and Tensor in NumPy**

In [9]:
#Scalar = single number
scalar=1.0
print(scalar)
print("Type of scalar", type(scalar))

print("-"*40)

#Vector -> 1D data
vector = np.array(
    [3,5,7]
)
print(vector)
print("Shape of Vector", vector.shape)

print("-"*40)
#Matrix data

matrix = np.array([[1,2,3],
                  [4,5,6]
                ])

print(matrix)
print("Shape of Matrix", matrix.shape)
print("-"*40)

tensor=np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [11,12,13],
            [14,15,16]
        ]
    ]
)

print(tensor)
print("Shape of Matrix", tensor.shape)
print("-"*40)

1.0
Type of scalar <class 'float'>
----------------------------------------
[3 5 7]
Shape of Vector (3,)
----------------------------------------
[[1 2 3]
 [4 5 6]]
Shape of Matrix (2, 3)
----------------------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
Shape of Matrix (2, 2, 3)
----------------------------------------


### **2. Creating Vectors and Matrices for ML Style Data**

In [11]:
#Imagine we have 3 samples and 2 features
# Feature1: hours studied
# Feature2: Number of questions solved
# target - Passed(1)/Fail(0)


X=np.array(
    [
        [2,30],   #Sample1
        [5,80],   #Sample2
        [1,20]    #Sample3
    ]
)


y=np.array(
    [0,1,0]
)

print("Input Data Matrix X:\n",X)
print("X Shape", X.shape) #(n_samples, n_features)

print("Output Vector: y:\n",y)
print("Y Shape", y.shape)


#A single sample as a vector
x1=X[0]

print("\n First sample as a vector:",x1)
print("\nx1 Shape:",x1.shape)


Input Data Matrix X:
 [[ 2 30]
 [ 5 80]
 [ 1 20]]
X Shape (3, 2)
Output Vector: y:
 [0 1 0]
Y Shape (3,)

 First sample as a vector: [ 2 30]

x1 Shape: (2,)


# **3. Basic Operations: Addition, Scalar Multiplication, Transpose**

In [26]:
#Create two vectors with same length
v1= np.array([1,2,3])
v2= np.array([4,5,6])

print("v1:",v1)
print("v2:",v2)

v_add=v1+v2

print("Vector addition v1+v2:",v_add)


#Scalar Multiplication

v1_scaled= 2 * v1
print("Vector addition 2 * v1:",v1_scaled)

#Matrics Example

A = np.array(
    [
      [1,2],
      [3,4]
    ]
)
B = np.array(
    [
      [10,20],
      [30,40]
    ]
)


print("Matrix A:\n",A)
print("Matrix B:\n",B)

#Matrix addition
print("Matrix Addition A + B:\n", A+B)

#Scalar Multiplication

print("Scalar Multiplication 0.5*A\n",0.5 *A)

#Matrix Transpose

print("Transpose of A:\n", A.T)



v1: [1 2 3]
v2: [4 5 6]
Vector addition v1+v2: [5 7 9]
Vector addition 2 * v1: [2 4 6]
Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[10 20]
 [30 40]]
Matrix Addition A + B:
 [[11 22]
 [33 44]]
Scalar Multiplication 0.5*A
 [[0.5 1. ]
 [1.5 2. ]]
Transpose of A:
 [[1 3]
 [2 4]]
